INVENTORY:
  DEFAULT:
#Mandatory Parameters-----------------------------------------------------------------------------------

    # Specify the port to be used by HPE 3PAR plugin etcd cluster
    host_etcd_port_number: 23790
    # Plugin Driver - iSCSI
    hpedockerplugin_driver: hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
    hpe3par_ip: 192.168.1.50
    hpe3par_username: 3paradm
    hpe3par_password: 3pardata
    hpe3par_port: 8080
    hpe3par_cpg: FC_r6

    # Plugin version - Required only in DEFAULT backend
    volume_plugin: hpestorage/legacyvolumeplugin:3.0
    # Dory installer version - Required for Openshift/Kubernetes setup
    # Supported versions are dory_installer_v31, dory_installer_v32
    dory_installer_version: dory_installer_v32

#Optional Parameters------------------------------------------------------------------------------------

    # Uncomment to encrypt passwords in hpe.conf using defined passphrase
    #encryptor_key: < encrypt_key1 >
    
    #ssh_hosts_key_file: '/root/.ssh/known_hosts'
    logging: DEBUG
    #hpe3par_debug: True
    #suppress_requests_ssl_warning: True
    #hpe3par_snapcpg: FC_r6
    #hpe3par_iscsi_chap_enabled: True
    #use_multipath: False
    #enforce_multipath: False
    #vlan_tag: True

#Optional Replication Parameters------------------------------------------------------------------------
    #replication_device:
    #  backend_id: remote_3PAR
    #  replication_mode: synchronous
    #  cpg_map: "local_CPG:remote_CPG"
    #  snap_cpg_map: "local_copy_CPG:remote_copy_CPG"
    #  hpe3par_ip: 192.168.2.50
    #  hpe3par_username: 3paradm
    #  hpe3par_password: 3pardata
    #  hpe3par_port: 8080
    #  vlan_tag: False

#Mandatory Parameters for Filepersona-----------------------------------------------------------------------------------
  DEFAULT_FILE:
    # Specify the port to be used by HPE 3PAR plugin etcd cluster
    host_etcd_port_number: 23790
    # Plugin Driver - File driver
    hpedockerplugin_driver: hpedockerplugin.hpe.hpe_3par_file.HPE3PARFileDriver
    hpe3par_ip: 192.168.2.50
    hpe3par_username: demo_user
    hpe3par_password: demo_pass
    hpe3par_cpg: demo_cpg
    hpe3par_port: 8080
    hpe3par_server_ip_pool: 192.168.98.3-192.168.98.10:255.255.192.0 
#Optional Parameters for Filepersona-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
    hpe3par_default_fpg_size: 16

#Additional Backend (Optional)--------------------------------------------------------------------------
  
  3PAR1:
#Mandatory Parameters-----------------------------------------------------------------------------------

    # Specify the port to be used by HPE 3PAR plugin etcd cluster
    host_etcd_port_number: 23790
    # Plugin Driver - Fibre Channel
    hpedockerplugin_driver: hpedockerplugin.hpe.hpe_3par_fc.HPE3PARFCDriver
    hpe3par_ip: 192.168.2.50
    hpe3par_username: 3paradm
    hpe3par_password: 3pardata
    hpe3par_port: 8080
    hpe3par_cpg: FC_r6

#Optional Parameters------------------------------------------------------------------------------------

    # Uncomment to encrypt passwords in hpe.conf using defined passphrase
    #encryptor_key: < encrypt_key2 >
    
    #ssh_hosts_key_file: '/root/.ssh/known_hosts'
    logging: DEBUG
    #hpe3par_debug: True
    #suppress_requests_ssl_warning: True
    hpe3par_snapcpg: FC_r6
    #use_multipath: False
    #enforce_multipath: False
