- name: Initialize the default parameters
  set_fact:
    install_etcd_hpe: false
    etcd_version_result : {}
    etcd_version: "2.3.7"

- name: Check whether etcd for hpe3parvolumeplugin is installed in /usr/bin/etcd
  stat:
    path: /usr/bin/etcd
  register: etcd_location_match

- name: Set flag for etcd_hpe installation if there is no etcd installed at /usr/bin/etcd
  set_fact: 
    install_etcd_hpe: true
  when: etcd_location_match.stat.exists == false

- name: Check already installed etcd version
  shell: /usr/bin/etcd --version |grep etcd
  register: etcd_version_result
  when: etcd_location_match.stat.exists  == true

- name: Fail when etcd version other than 2.3.7 is present in /usr/bin/etcd
  fail:
    msg: "Already installed etcd version is not 2.3.7, terminating the etcd installation.\n Please manually uninstall the existing etcd in /usr/bin/etcd folder and perform the installation."
  when: install_etcd_hpe == false and '2.3.7' not in etcd_version_result.stdout

- name : Create tmp/hpe_etcd directory
  file:
     path: /tmp/hpe_etcd
     state: directory
  when: install_etcd_hpe == true

- name : Download the etcdv2.3.7 binary
  get_url:
    url:  https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /tmp/hpe_etcd
  when: install_etcd_hpe == true

- name: Install binary
  shell: |
    cd /tmp/etcd
    tar xzvf etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    cd etcd-v{{ etcd_version }}-linux-amd64
    mv etcd etcdctl /usr/bin
    chmod 755 /usr/bin/etcd /usr/bin/etcdctl
  when: install_etcd_hpe == true

- name : delete tmp/hpe_etcd directory
  file:
    path: /tmp/hpe_etcd
    state: absent
  when: install_etcd_hpe == true  
